export const SHOW_ALERT = 'APP/SHOW_ALERT';
export const HIDE_ALERT = 'APP/HIDE_ALERT';
export const TOGGLE_CURRENCY = 'APP/TOGGLE_CURRENCY';

export const SET_CATEGORIES = 'SHOP/SET_CATEGORIES';
export const FETCH_PRODUCTS = 'SHOP/FETCH_PRODUCTS';
export const SHOW_ACTIVE_PRODUCTS = 'SHOP/SHOW_ACTIVE_PRODUCTS';
export const CHOICE_PAGINATION_INDEX = 'SHOP/CHOICE_PAGINATION_INDEX';
export const CLEAR_PAGINATION_INDEX = 'SHOP/CLEAR_PAGINATION_INDEX';
export const GET_SINGLE_PRODUCT = 'SHOP/GET_SINGLE_PRODUCT';

export const LOGIN = 'AUTH/LOGIN';
export const LOGOUT = 'AUTH/LOGOUT';

export const ADD_TO_CART = 'CART/ADD_TO_CART';
export const REMOVE_FROM_CART = 'CART/REMOVE_FROM_CART';
export const INCREASE_QUANTITY = 'CART/INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'CART/DECREASE_QUANTITY';
